---
apiVersion: v1
kind: Pod
metadata:
  name: java-18-sws-pod
  app: java-18-sws
spec:
  containers:
  - name: java-18-sws-container
    image: quay.io/tomerfi/java-18-simple-web-server:dev
    ports:
    - containerPort: 8000
    env:
    - name: TXT_TST
      value: "Hello testing 2"
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"

