---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: ManagedClusterSetBinding
metadata:
  name: java-18-sws-clusterset
  namespace: java-18-sws-app-ns
spec:
  clusterSet: java-18-sws-clusterset
