apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: java-18-simple-web-server/manifests
    apps.open-cluster-management.io/git-clone-depth: "1"
    apps.open-cluster-management.io/reconcile-option: merge
    apps.open-cluster-management.io/reconcile-rate: high
  name: java-18-sws-subscription
  namespace: java-18-sws-app-ns
spec:
  channel: java-18-sws-chan-ns/git-ocm-playground
  placement:
    placementRef:
      kind: Placement
      name: java-18-sws-placement
