apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: java-18-simple-web-server/manifests
  name: java-18-sws-subscription
spec:
  channel: git-ocm-playground
  placement:
    placementRef:
      kind: PlacementRule
      name: java-18-sws-placement-rule
